wip/6.0 Reuse ArrayHelper's empty array constant to avoid object creation
hibernate/hibernate-orm pull request #3493
Opened 2020-08-07 01:24 UTC by NathanQingyangXu

We have the following empty array constants in `org.hibernate.internal.util.collections.ArrayHelper`:
```
        public static final String[] EMPTY_STRING_ARRAY = {};
	public static final int[] EMPTY_INT_ARRAY = {};
	public static final boolean[] EMPTY_BOOLEAN_ARRAY = {};
	public static final Class[] EMPTY_CLASS_ARRAY = {};
	public static final Object[] EMPTY_OBJECT_ARRAY = {};
	public static final Type[] EMPTY_TYPE_ARRAY = {};
	public static final byte[] EMPTY_BYTE_ARRAY = {};
```

This PR aims to reuse these constant in lieu of empty array creation to boost performance. Given the array is empty, it seems the replacement is hassle-free.

2020-08-07 02:32 UTC, NathanQingyangXu commented on hibernate-core/src/main/java/org/hibernate/action/internal/BulkOperationCleanupAction.java
> +		this.affectedTableSpaces = spacesList.toArray( ArrayHelper.EMPTY_STRING_ARRAY );
In modern JVM, `spacesList.toArray( new String[0] )` is faster than `spacesList.toArray( new String[ spacesList.size() ] )`. E.g. https://stackoverflow.com/questions/174093/toarraynew-myclass0-or-toarraynew-myclassmylist-size

Similar changes are done elsewhere in this PR.

2021-01-12 08:15 UTC, beikov commented
Why did you close the PR? I wasn't aware of it, but I would consider merging parts of it if you would agree to change/revert a few things.

2021-01-12 13:19 UTC, NathanQingyangXu commented
I've thought this PR is too minor to be serious., :). I am gonna reopen it
to let you review it.

On Tue., Jan. 12, 2021, 03:16 Christian Beikov, <notifications@github.com>
wrote:

> Why did you close the PR? I wasn't aware of it, but I would consider
> merging parts of it if you would agree to change/revert a few things.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/hibernate/hibernate-orm/pull/3493#issuecomment-758486915>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB6UYARKWFGVPMSEJMVNNETSZQAMBANCNFSM4PXEN47Q>
> .
>

2021-01-13 10:12 UTC, beikov requested changes
Please remove the unnecessary imports, then I will merge it

2021-01-13 10:12 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/JPAOverriddenAnnotationReader.java
> +import org.hibernate.internal.util.collections.ArrayHelper;
Revert please
```suggestion
```

2021-01-13 10:12 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
> +import org.hibernate.internal.util.collections.ArrayHelper;
Revert please
```suggestion
```

2021-01-13 13:30 UTC, NathanQingyangXu commented on hibernate-core/src/main/java/org/hibernate/cfg/annotations/reflection/JPAOverriddenAnnotationReader.java
> +import org.hibernate.internal.util.collections.ArrayHelper;
done. thanks.

2021-01-13 13:30 UTC, NathanQingyangXu commented on hibernate-core/src/main/java/org/hibernate/engine/spi/ActionQueue.java
> +import org.hibernate.internal.util.collections.ArrayHelper;
done. thanks.

2021-01-13 13:35 UTC, merged