HHH-14178 Fix the issue collections visiting could be skipped in AbstractSaveEventListener
hibernate/hibernate-orm pull request #3513
Opened 2020-08-24 02:47 UTC by NathanQingyangXu

https://hibernate.atlassian.net/browse/HHH-14178

It seems the root cause is side-effect + short-circuiting.

2020-08-24 02:49 UTC, NathanQingyangXu commented on hibernate-core/src/main/java/org/hibernate/event/internal/AbstractSaveEventListener.java
> +			substitute = substitute || substituteBecauseOfCollections;
`visitCollectionsBeforeSave()` is a method with side effect. The side effect would not happen if `substitute` has been true (e.g., versioned entity) due to boolean operator short-circuiting.

2020-08-24 13:23 UTC, beikov commented
Would you mind integrating the test case that was attached to the issue so we avoid the same problem for 6.0?

2020-08-24 14:25 UTC, gavinking commented
Replicated fix in HR: https://github.com/hibernate/hibernate-reactive/commit/569caf1444c63f311b200505fc62fce720ef08dc

2020-08-24 19:47 UTC, NathanQingyangXu commented
> Would you mind integrating the test case that was attached to the issue so we avoid the same problem for 6.0?

Testing cases added. Maintained the original logic as much as possible. However, the original testing cases are too verbose and some of them are not needed. Also, an important testing scenario was overlooked (versioned map + versioned mapping).

2020-08-31 09:08 UTC, beikov requested changes
Apart from a small issue, looks good!

2020-08-31 09:08 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java
> +	private static boolean isCollectionNewlyInstantiated(PersistentCollection pc) {
Remove

2020-08-31 10:00 UTC, NathanQingyangXu commented on hibernate-core/src/main/java/org/hibernate/engine/internal/Cascade.java
> +	private static boolean isCollectionNewlyInstantiated(PersistentCollection pc) {
done. thanks for spotting this.

2020-08-31 10:02 UTC, beikov approved these changes

2020-08-31 12:43 UTC, merged