Fix issues with FK creation
hibernate/hibernate-orm pull request #3735
Opened 2021-02-15 17:00 UTC by beikov

2021-02-24 17:44 UTC, dreab8 approved these changes

2021-02-24 18:08 UTC, sebersole approved these changes
Really liked the changes to `BulkOperationCleanupAction` based on the SqmStatement - very clean

2021-02-24 18:34 UTC, sebersole requested changes
Actually this leads to tests failures that are repeatable.  Could you take a look at why?

2021-02-24 19:16 UTC, sebersole commented
FWIW I applied my latest work for natural-id on top of this and the changes here resolve the database snapshot issues I was having

2021-02-25 09:49 UTC, beikov commented
You are right @sebersole I fixed that now. Apparently Derby does not like plain `null` as select item because it can't infer a type. I now implemented casts of plain parameters and `null` when appearing as select item.

2021-02-25 11:08 UTC, merged