Wip/6.0 re enabling tests
hibernate/hibernate-orm pull request #4080
Opened 2021-07-02 17:11 UTC by dreab8

2021-07-07 11:58 UTC, beikov requested changes

2021-07-07 11:58 UTC, beikov commented on hibernate-core/src/test/java/org/hibernate/orm/test/ops/MergeManagedAndCopiesAllowedTest.java
> + * D 1------------>N E
I believe this formatting change was not intentional?

2021-07-07 11:58 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/boot/query/HbmResultSetMappingDescriptor.java
> +		return new NamedResultSetMappingMementoImpl( registrationName, resultMementos, fetchBuilderLegacies );
Shouldn't this be handled by `EntityResultDescriptor#resolve` where the join descriptors are resolved into fetch mementos?

2021-07-07 11:58 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java
> +	private void processRootReturn(NativeQuery.EntityReturn rootReturn) {
Maybe you should rename the method to `processEntityReturn` and also the variables that refer to such a type accordingly to `entityReturn`

2021-07-07 11:58 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/query/sql/internal/ResultSetMappingProcessor.java
> +	private void addPersister(String alias, Map<String, String[]> propertyResult, String suffix, SQLLoadable persister) {
Is this even used?

2021-07-07 14:28 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/query/sqm/sql/BaseSqmToSqlAstConverter.java
> +		// add any additional join restrictionsHbmResultSetMappingDescriptor.java
Typo

```suggestion
		// add any additional join restrictions
```

2021-07-08 12:50 UTC, merged

2021-07-08 12:51 UTC, dreab8 commented
Thanks @beikov for the review and great help!