HHH-17310 Bug with names with digits in CamelCaseToUnderscoresNamingStrategy
hibernate/hibernate-orm pull request #7566
Opened 2023-11-22 15:38 UTC by anilabhabaral

https://hibernate.atlassian.net/browse/HHH-17310

2023-11-27 11:58 UTC, anilabhabaral commented
Hello @ChristianHoesel  @gavinking could you please take a look and review this PR. I am very new to this repository and trying to contribute in this project. Thanks.

2023-12-19 19:26 UTC, beikov commented
Please also add a test case. Without that, we can't merge such a change.

2023-12-20 09:11 UTC, anilabhabaral commented
Thanks @beikov I will add the test case for the changes.

2023-12-20 16:36 UTC, anilabhabaral commented
Hi @beikov i added the testcase for the changes. Please check. Thanks!

2024-01-09 13:24 UTC, anilabhabaral commented
Hello @beikov @mbladel could you please review this PR. Thanks!

2024-07-05 17:21 UTC, anilabhabaral commented
Hello @beikov @mbladel could you please review this PR? Let me know if any modification is needed. Thanks

2024-08-28 22:13 UTC, gavinking requested changes
Please see my comment.

Perhaps I've misunderstood, but then I would like to see something properly documenting all the cases that this slightly-complicated new logic is dealing with.

2024-08-28 22:13 UTC, gavinking commented on hibernate-core/src/main/java/org/hibernate/boot/model/naming/CamelCaseToUnderscoresNamingStrategy.java
> +			}
So `hello1` -> `hello_1`? I don't think I see why that's correct.

It seems to me that we should simply be treating digits exactly as we treat lowercase characters, no?

2024-08-28 22:16 UTC, gavinking commented on hibernate-core/src/main/java/org/hibernate/boot/model/naming/CamelCaseToUnderscoresNamingStrategy.java
> +		}
A bit naively, seems to me that you could simply delete this whole block. What am I missing?

```suggestion
```

2024-08-29 08:58 UTC, gavinking commented on hibernate-core/src/main/java/org/hibernate/boot/model/naming/CamelCaseToUnderscoresNamingStrategy.java
> +		}
Yep, sounds good to me. Thanks!

2024-08-29 09:50 UTC, anilabhabaral commented
Hello @gavinking i have done the suggested changes. Please check.

2024-08-29 10:23 UTC, gavinking requested changes
Would you please squash the commits and apply the suggested change to the code formatting?

Thanks.

2024-08-29 10:23 UTC, gavinking commented on hibernate-core/src/main/java/org/hibernate/boot/model/naming/CamelCaseToUnderscoresNamingStrategy.java
> +		return (Character.isLowerCase(before) || Character.isDigit(before)) && Character.isUpperCase(current) && (Character.isLowerCase(after) || Character.isDigit(after));
```suggestion
		return ( Character.isLowerCase( before ) || Character.isDigit( before ) ) 
			&& Character.isUpperCase( current ) 
			&& ( Character.isLowerCase( after ) || Character.isDigit( after ) );
```

2024-08-29 11:09 UTC, anilabhabaral commented
Seems like i messed up with my git branch. I will create a new PR.

2024-08-29 11:09 UTC, closed without merging