Hhh-17562 Allow disabling of  NaturalIDCaching
hibernate/hibernate-orm pull request #7724
Opened 2024-01-19 16:30 UTC by tg-freigmbh

https://hibernate.atlassian.net/browse/HHH-17562
Added a new Option to turn off Hibernates Natural-ID Cache. 
Motivation is that I ran into multiple bugs and performance problems involving that cache. It seems to me the cache is only usefull if someone uses the strange semantics of Session.byNaturalId to find objects from cache-> and for a lot of usecases you dont need to.
Having this Option "breaking" Hibernate functionality is a bit sad, however I would argue there is a huge problem by design if hibernate has to track each object in every usecase because someone might want to use NaturalLoadId in some usecases. 

Setting this Option will alter the behavior of Session.byNaturalID a bit -> Objects will be always looked up from the database, so if you change your natural id and didn't flush your entity to the database, you cant find it anymore.  

This option allows one to workaround HHH-17556-> no more exceptions because of bad caching.
As another argument for this change see included:
org.hibernate.orm.test.mapping.naturalid.performance.PerformanceTest
disabling the natural Id Resolutions Cache allows the test to complete as expected-> having it enabled will most likely (but not guaranteed) throw an StackoverflowError

Best regards

2024-01-19 17:52 UTC, sebersole commented
Love the idea, thanks!

2024-01-19 20:13 UTC, gavinking commented
> As another argument for this change see included: `org.hibernate.orm.test.mapping.naturalid.performance.PerformanceTest`

The reason for the stack overflow in that test is that you have an insane implementation of `equals()` that tries to recursively walk a linked list with 10k objects in it. The stack overflow has _nothing at all to do with caching_, and I can fix it by just changing to a non-insane implementation of `equals()`.

For example, with the following change, the test passes:

```java
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Node node)) return false;
            return node.getNextNode() == nextNode
                && Objects.equals(node.getOtherPart(),otherPart);
        }

        @Override
        public int hashCode() {
            return Objects.hash(ident, otherPart);
        }
```

> Motivation is that I ran into multiple bugs and performance problems involving that cache.

I strongly suspect that you're doing other insane things, such things being the actual source of your problems.

2024-01-19 20:14 UTC, gavinking commented
> Love the idea, thanks!

The idea might be OK, but the other claims made here are highly suspect.

2024-01-19 20:16 UTC, gavinking requested changes
DO NOT MERGE

2024-12-01 13:44 UTC, gavinking commented
Natural id caching is off by default. It’s only enabled when you explicitly annotate an entity with the `@NaturalIdCache` annotation. It's also disabled whenever the whole second-level cache is disabled, and it's easy to disable the second-level cache (it's even disabled by default).

Hibernate already has way too many switches and toggles; let's not add a new one here.

2024-12-01 13:44 UTC, closed without merging