HHH-18116 Support slow query logging for stored procedures
hibernate/hibernate-orm pull request #8382
Opened 2024-05-14 15:56 UTC by marschall

https://hibernate.atlassian.net/browse/HHH-18116

2024-05-15 11:31 UTC, gavinking requested changes
Unless I'm missing something, it seems to me that it be better to pass the SQL string to the constructor of `ProcedureOutputsImpl` and then to the constructor of `OutputsImpl`, instead of passing it as an argument to the `executeStatement()` method.

2024-05-15 11:31 UTC, gavinking commented on hibernate-core/src/main/java/org/hibernate/procedure/internal/ProcedureCallImpl.java
> +		String sqlString = call.getSqlString();
```suggestion
		final String sqlString = call.getSqlString();
```

2024-05-15 11:31 UTC, gavinking commented on hibernate-core/src/main/java/org/hibernate/result/internal/OutputsImpl.java
> +		if ( this.sqlStatementLogger.getLogSlowQuery() > 0 ) {
```suggestion
		if ( sqlStatementLogger.getLogSlowQuery() > 0 ) {
```

2024-05-16 09:03 UTC, marschall commented
> Unless I'm missing something, it seems to me that it be better to pass the SQL string to the constructor of `ProcedureOutputsImpl` and then to the constructor of `OutputsImpl`, instead of passing it as an argument to the `executeStatement()` method.

Fair point, corrected.

2024-05-16 12:22 UTC, gavinking approved these changes
LGTM, thanks!

2024-05-16 17:38 UTC, merged