Improve partial order algorithm in AnnotationMetadataSourceProcessorImpl
hibernate/hibernate-orm pull request #8635
Opened 2024-07-05 03:02 UTC by NathanQingyangXu

This PR aims to improve the partial order sorting issue in AnnotationMetadataSourceProcessorImpl in terms of readability and complexity.

2024-07-05 03:06 UTC, NathanQingyangXu commented on hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
> +		return orderedXClasses;
the diff was screwed up by github, ending up with more difficult code review

2024-07-08 15:45 UTC, beikov requested changes
Looks ok, but I would like to ask you to avoid the use of `LinkedList` and the multiple instance creations.

2024-07-08 15:45 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
> +		LinkedHashSet<XClass> orderedClasses = CollectionHelper.linkedSetOfSize( classes.size() * 2 );
```suggestion
		LinkedHashSet<XClass> orderedClasses = CollectionHelper.linkedSetOfSize( classes.size() * 2 );
		ArrayList<XClass> clazzHierarchy = new ArrayList<>();
```

2024-07-08 15:45 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
> +				LinkedList<XClass> clazzHierarchy = new LinkedList<>();
```suggestion
				clazzHierarchy.clear();
```

2024-07-08 15:45 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
> +						clazzHierarchy.addFirst( superClass ); // ensure ancestors shows up earlier
```suggestion
						clazzHierarchy.add( superClass );
```

2024-07-08 15:45 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
> +				orderedClasses.addAll( clazzHierarchy );
```suggestion
				// ensure ancestors shows up earlier
				for ( int i = clazzHierarchy.size() - 1; i >= 0; i-- ) {
					orderedClasses.add( clazzHierarchy.get( i ) );
				}
```

2024-07-08 18:47 UTC, NathanQingyangXu commented on hibernate-core/src/main/java/org/hibernate/boot/model/source/internal/annotations/AnnotationMetadataSourceProcessorImpl.java
> +						clazzHierarchy.addFirst( superClass ); // ensure ancestors shows up earlier
changed as suggested. thanks!

2024-07-09 12:31 UTC, merged