HHH-18339 Set support filter clause to True for H2
hibernate/hibernate-orm pull request #8640
Opened 2024-07-05 14:19 UTC by SamuelGuillemet

H2 supports the filter clause (as it can be seen [here](https://www.h2database.com/html/functions-aggregate.html)) but in the H2SqlAstTranslator the supportsFilterClause is not overridden to be set to true.

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

2024-07-05 14:38 UTC, beikov commented
You write in the Jira issue that this is a bug quoting `In the org.hibernate.dialect.function.array.ArrayAggFunction::renderfunction the filter is wrapped in a case statement resulting in error when the filter predicate is, for example, set to WHERE smth IS NOT NULL`

What is the query that reproduces this problem and the stack trace?

I see that the `FILTER` clause is supported [since 1.4.197](https://github.com/h2database/h2database/commit/9e6dbf3baa57000f670826ede431dc7fb4cd9d9c), so the change is fine, but we need a test.

2024-07-05 19:11 UTC, SamuelGuillemet commented
The initial description was somewhat misleading, as there is no direct bug or exception thrown. Instead, the issue lies with the SQL generated by any aggregation function, specifically observed while working with the `ArrayAggFunction`.

## Code Example

Here is the Java code that demonstrates the issue:

```java
final NodeBuilder cb = (NodeBuilder) em.getCriteriaBuilder();
final JpaCriteriaQuery<String[]> cq = cb.createQuery(String[].class);
final JpaRoot<EntityOfBasics> root = cq.from(EntityOfBasics.class);
Expression<String> expr = root.get("theString");
JpaOrder order = cb.desc(expr);
JpaPredicate predicate = cb.isNotNull(expr);
cq.select(cb.arrayAgg(order, predicate, expr));
List<String[]> results = em.createQuery(cq).getResultList();
assertEquals(1, results.size());

// Without the support of the filter clause
assertArrayEquals(new String[]{null, "def", "abc"}, results.get(0));

// With the support of the filter clause
assertArrayEquals(new String[]{"def", "abc"}, results.get(0));
```

## Issue Explanation

When there is no support for the `FILTER` clause, the `render` function of the `ArrayAggFunction` class sets the `caseWrapper` field to `true`. This causes the `isNotNull` filter to be wrapped in a `CASE` statement.

### SQL Output Without `FILTER` Clause Support

The generated SQL is as follows:

```sql
SELECT array_agg(CASE WHEN a.theString IS NOT NULL THEN a.theString ELSE NULL END ORDER BY a.theString DESC) 
FROM EntityOfBasics a;
```

### Expected SQL Output With `FILTER` Clause Support

With support for the `FILTER` clause, the expected SQL would be:

```sql
SELECT array_agg(a.theString ORDER BY a.theString DESC) 
FILTER (WHERE a.theString IS NOT NULL) 
FROM EntityOfBasics a;
```

The second query correctly excludes `NULL` values from the result.

## Impact

The lack of support for the `FILTER` clause leads to inclusion of `NULL` values in the results, which could lead to potential errors.

2024-07-08 16:07 UTC, beikov requested changes
Please also add the following to `H2LegacySqlAstTranslator`

```java
	@Override
	public boolean supportsFilterClause() {
		return getVersion().isSameOrAfter( 1, 4, 197 );
	}
```

2024-07-08 16:07 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/dialect/H2SqlAstTranslator.java
> +		// Filter clause is in the abstract base class of Aggregate https://github.com/h2database/h2database/blame/master/h2/src/main/org/h2/expression/aggregate/AbstractAggregate.java#L52
```suggestion
```

2024-07-09 13:58 UTC, merged