HHH-18358 Metemodel generator does not resolving entity type literals
hibernate/hibernate-orm pull request #8651
Opened 2024-07-09 20:10 UTC by cigaly

See Jira issue [HHH-18358](https://hibernate.atlassian.net/browse/HHH-18358)

When generating metamodel named query defined as

```@NamedQuery(name = "#simple", query = "select s from Simple s where type(s) = Simple")```

causing generation to fail with error message

```Could not interpret path expression 'Simple'```

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

2024-07-10 21:14 UTC, gavinking requested changes
@cigaly Thanks for the contribution!

I have two comments:

1. I would prefer to keep all this down on `ProcessorSessionFactory` instead of leaking it up the `MockSessionFactory`.
2. Do we *really* need a separate `Map` with all the resulting allocating instead of just doing a linear search on the `Map` we already have?

2024-07-11 08:49 UTC, cigaly commented
@gavinking Thanks for comments. I've changed code according to your two points and slightly changed it to return null when type name does not correspond to (known) entity.

2024-07-11 12:18 UTC, gavinking commented on tooling/metamodel-generator/src/main/java/org/hibernate/processor/validation/ProcessorSessionFactory.java
> +					&& !typeUtil.isSameType( persister.type.asType(), type.asType() );
Wait, I don't think this change is quite correct.

I believe that `isSubclassEntityName()` is supposed to return `true` when passed the name of the current entity.

i.e. we consider `T` to be a subtype of `T`.

2024-07-13 09:32 UTC, merged

2024-07-13 09:33 UTC, gavinking commented
Thanks!!!

2024-07-13 10:04 UTC, cigaly commented
@gavinking Unfortunately, there is problem with this solution. My assumption that we can return null if entity is not know is simply wrong. This can be reference to some entity that is not processed yet, but will be during further processing.

I've fixed that with pull request [#8666](https://github.com/hibernate/hibernate-orm/pull/8666) to create entity assuming that entity name is equal to type name.

Best solution will be to collect all entites (mapperd superclasses, embeddables, ...?) in advance, but I am not sure if this is good idea or not.