HHH-18454 - Skip connection provider retrieval and DB info logging when booting offline
hibernate/hibernate-orm pull request #8745
Opened 2024-08-01 16:11 UTC by jrenaat

[Please describe here what your change is about]

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

2024-08-03 23:48 UTC, gavinking commented on hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
> +		logDbInfo( isJdbcMetadataAccessAllowed, registry, jdbcEnvironment );
@jrenaat why not just move the call to `logDbInfo()` inside the first block of the `if`? That's simpler and clearer, no?

2024-08-05 16:45 UTC, sebersole requested changes
Looks much better, thanks!

Just a minor change I requested.

2024-08-05 16:45 UTC, sebersole commented on hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java
> +	private DatabaseConnectionInfo buildDbInfo(boolean isJdbcMetadataAccessAllowed, ServiceRegistryImplementor registry, Map<String, Object> configurationValues) {
I'd split these into separate methods.  Its minor, but we've already done this if-check in the enclosing callers.

2024-08-05 20:12 UTC, sebersole approved these changes

2024-08-05 20:14 UTC, merged