Failing test to demonstrate HHH-18466
hibernate/hibernate-orm pull request #8765
Opened 2024-08-07 13:47 UTC by garydgregory

https://hibernate.atlassian.net/browse/HHH-18466

This test demonstrates a regression from 5.6.15.Final: When you have an entity with more than one `@NaturalID` instance variable, and you mutate those fields, that entity can no longer be found. There is no workaround that I can find.

Here is a PR (also attached as a patch) with a failing test called `MutableNaturalIdsTest`

Tested with:
```
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```
and
```
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
```

2024-08-08 14:40 UTC, garydgregory commented
Hi All, 

Is there any chance this fix can be in the upcoming 6.6.0 release? Or 6.5.x if there is one?

The "Pipeline" job has been running for 12+ hours it seems. That can't be normal can it? All other jobs are green.

2024-08-15 13:09 UTC, sebersole requested changes
As I mentioned on the JIra, I think the Javadoc for `NaturalIdMapping#isMutable` is just wrong, compounding the confusion here.

Would you be willing to add that change here @garydgregory?  Thanks

2024-08-15 14:40 UTC, garydgregory commented
@sebersole 
Done!

2024-08-15 14:47 UTC, sebersole approved these changes

2024-08-15 17:27 UTC, merged