HHH-18475 fix race condition in AbstractRowMapper
hibernate/hibernate-orm pull request #8774
Opened 2024-08-12 08:40 UTC by obourgain

Fix race condition in AbstractRowMapper. Described in the Jira https://hibernate.atlassian.net/browse/HHH-18475

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

2024-08-13 02:02 UTC, quaff commented
Good catch.

2024-08-28 19:32 UTC, gavinking requested changes
Please include the test which reproduces the problem as part of this PR. Thanks.

2024-09-12 14:27 UTC, merged

2024-09-12 14:28 UTC, beikov commented
Thanks for the fix. I checked the code paths and this indeed looks like a concurrency issue.

2024-09-12 14:37 UTC, obourgain commented
Thank you.

2026-10-09 18:13 UTC, vsachinv commented
@obourgain In which version this fix is available of 5.6.x line?

2026-10-09 18:53 UTC, obourgain commented
I'm not sure that was released. I since upgraded the affected app to 6.x

2026-10-19 12:58 UTC, vsachinv commented
@obourgain Thanks.

@beikov Could you please help on this ?

2026-10-27 16:50 UTC, beikov commented
It was merged, but we didn't release a new ORM 5.6 version ever since.