Mark field `INSTANCE` as private if method `instance()` present
hibernate/hibernate-orm pull request #8799
Opened 2024-08-20 08:14 UTC by quaff

[Please describe here what your change is about]

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

2024-08-28 19:30 UTC, gavinking approved these changes
This looks OK to me.

2024-09-12 14:20 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/type/descriptor/java/Immutability.java
> +	private static final Immutability INSTANCE = new Immutability();
Please revert and deprecate for removal instead. This is an SPI, so we'd have to first deprecate the field.

2024-09-12 14:20 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/type/descriptor/java/ImmutableMutabilityPlan.java
> +	private static final ImmutableMutabilityPlan INSTANCE = new ImmutableMutabilityPlan();
Please revert and deprecate for removal instead. This is an SPI, so we'd have to first deprecate the field.

2024-09-12 14:20 UTC, beikov commented on hibernate-core/src/main/java/org/hibernate/sql/results/spi/ScrollableResultsConsumer.java
> +	private static final ScrollableResultsConsumer INSTANCE = new ScrollableResultsConsumer();
Please revert and deprecate for removal instead. This is an SPI, so we'd have to first deprecate the field.

2024-09-12 14:21 UTC, beikov requested changes
Other than what I commented, this looks good to me.

2024-09-13 00:59 UTC, quaff commented
> Other than what I commented, this looks good to me.

done.

2024-09-13 09:03 UTC, merged

2024-09-13 09:03 UTC, beikov commented
Thanks