Restore hibernate.jdbc.batch_versioned_data function.
hibernate/hibernate-orm pull request #8864
Opened 2024-08-31 23:23 UTC by ettavolt

batch_versioned_data=false is particularly useful to enable reporting the exact entity that failed optimistic lock.

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

2024-08-31 23:27 UTC, ettavolt commented
I feel like this might be covering https://hibernate.atlassian.net/browse/HHH-10501. May I use it as the required Jira reference?

2024-09-08 08:09 UTC, gavinking commented
> I feel like this might be covering https://hibernate.atlassian.net/browse/HHH-10501. 

It is not.

> May I use it as the required Jira reference?

No, please open a new issue with a proper description of the problem you're fixing. Thanks.

2024-09-16 07:11 UTC, gavinking commented
> batch_versioned_data=false is particularly useful to enable reporting the exact entity that failed optimistic lock.

Since HHH-18586, Hibernate 7 reports a proper `StaleObjectStateException` when a batch update fails.

Which means that your test will pass even without this fix.

2024-09-16 07:17 UTC, gavinking commented
(FTR, the actual fix looks reasonable to me, though I'm not an expert on that code.)

2024-09-16 07:18 UTC, gavinking requested changes
> Which means that your test will pass even without this fix.

Confirmed by running the test locally.

So needs a different test.

2025-02-08 14:30 UTC, gavinking commented
Thanks for the contribution, but without a test for the functionality I could not apply the fix. Instead I decided to remove the functionality: https://github.com/hibernate/hibernate-orm/pull/9717

2025-02-08 14:30 UTC, closed without merging