HHH-18685 proposed basic enhancement to allow subclasses to have alre…
hibernate/hibernate-orm pull request #9049
Opened 2024-10-03 20:29 UTC by bodhi-one

…ady initialized the HikariDataSource

Provide HikariCPConnectionProvider ability to use a pre-configured HikariDataSource already initialized by subclasses. Many more details in the Jira.

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

2024-10-04 08:27 UTC, beikov requested changes
Not sure if want to allow this, but the code can be cleaned up.

2024-10-04 08:27 UTC, beikov commented on hibernate-hikaricp/src/main/java/org/hibernate/hikaricp/internal/HikariCPConnectionProvider.java
> +			}
```suggestion
			// Support a HikariDataSource already configured by classes which extend this class
			if ( props.get("HikariDataSource") instanceof HikariDataSource hikariDataSource ) {
				hds = hikariDataSource;
			}
			else {
				// Default logic if no subclass has configured a HikariDataSource, do so now
				hds = new HikariDataSource( hcfg );
			}
```

2024-10-08 14:03 UTC, bodhi-one commented
Changes made as requested.

2024-10-09 07:30 UTC, beikov commented
Please also squash and rebase the commits.

2024-10-09 15:26 UTC, bodhi-one commented
Hi @beikov , sorry, myself and another very smart guy tried to do this, but we are having issues, can you please give us exact steps.

git rebase -i HEAD~2
error: cannot 'squash' without a previous commit
You can fix this with 'git rebase --edit-todo' and then run 'git rebase --continue'.
Or you can abort the rebase with 'git rebase --abort'.

2024-10-16 15:42 UTC, bodhi-one commented
> Since `HikariDataSource` is a `DataSource` why not just use `DatasourceConnectionProviderImpl`?

Hi @sebersole - we have already bootstrapped HikariCP, Hibernate will next call looking for the ConnectionProvider, and it will bypass our HikariDataSource, already created by us because of our unique configuration, we just need HikariCPConnectionProvider to allow us to provide our HikariDataSource in place of creating another one.   If we extended a non-Hikari Hibernate class, wouldn't that prevent us from being wired up into the existing HikariCP pools (that we just created) ?

2024-10-16 17:11 UTC, beikov commented
You are clearly configuring Hibernate ORM in a programmatic fashion since you pass an object `HikariDataSource` as value somehow. Instead of changing the `HikariCPConnectionProvider` implementation, you could rather use `DatasourceConnectionProviderImpl` directly i.e. replace

```
  .setProperty("hibernate.hikari.HikariDataSource", hikariDataSource)
```

with

```
  DatasourceConnectionProviderImpl connectionProvider = new DatasourceConnectionProviderImpl();
  connectionProvider.setDataSource( hikariDataSource );
  .setProperty("hibernate.connection.provider_class", connectionProvider)
```

2024-10-16 17:11 UTC, closed without merging

2024-10-17 14:54 UTC, bodhi-one commented
> You are clearly configuring Hibernate ORM in a programmatic fashion since you pass an object `HikariDataSource` as value somehow. Instead of changing the `HikariCPConnectionProvider` implementation, you could rather use `DatasourceConnectionProviderImpl` directly i.e. replace
> 
> ```
>   .setProperty("hibernate.hikari.HikariDataSource", hikariDataSource)
> ```
> 
> with
> 
> ```
>   DatasourceConnectionProviderImpl connectionProvider = new DatasourceConnectionProviderImpl();
>   connectionProvider.setDataSource( hikariDataSource );
>   .setProperty("hibernate.connection.provider_class", connectionProvider)
> ```

Hi, I'm not following.  Do you mean for us to extend DatasourceConnectionProviderImpl or to submit a PR for these changes you outlined above directly into DatasourceConnectionProviderImpl.  

If you meant for us to extend DatasourceConnectionProviderImpl, then at what interaction would we override the base code with what you have suggested?

2024-10-17 15:13 UTC, sebersole commented
Have you looked at `DatasourceConnectionProviderImpl`?

Its hard to answer these *usage* questions without seeing your actual code.  The important bit here is when/how you create the HikariDataSource relative to when/how you bootstrap Hibernate.  But assuming "normal" start up, something like:

```java
HikariDataSource hikariDatasource = ...;
SessionFactory = new Configuration()
        .setProperty( "hibernate.connection.datasource", hikariDatasource )
        ...
        .buildSessionFactory();
```