HHH-18808 Fix the bug of wrong logging output when keyword is used as identifier in HqlParser.g4
hibernate/hibernate-orm pull request #9198
Opened 2024-11-04 06:47 UTC by NathanQingyangXu

https://hibernate.atlassian.net/browse/HHH-18808

Not sure why not move the keyword list into HqlLexer.g4, which would simplify a lot and I think we could still overwrite HqlLexer class. But here is a quick and effective bug fix.

2024-11-04 07:44 UTC, gavinking commented
I think we should simply remove that log message. It's not useful, IMO.

2024-11-05 00:21 UTC, NathanQingyangXu commented
> I think we should simply remove that log message. It's not useful, IMO.

If so, we could end up with lots of simplification to the ANTLR grammer, code or even perf.

2024-11-05 08:00 UTC, gavinking commented
> > I think we should simply remove that log message. It's not useful, IMO.
> 
> 
> 
> If so, we could end up with lots of simplification to the ANTLR grammer, code or even perf.

WDYM?

2024-11-05 08:49 UTC, gavinking requested changes

2024-11-05 08:49 UTC, gavinking commented on hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
> +	: ( ERROR | NULL | ( DEFAULT expression ) ) ON (ERROR|EMPTY)
Please roll back this change;it's inconsistent with the formatting of the rest of the BNF.

2024-11-05 08:49 UTC, gavinking commented on hibernate-core/src/main/antlr/org/hibernate/grammars/hql/HqlParser.g4
> +	: ( ERROR | NULL | ( DEFAULT expression ) ) ON (ERROR|EMPTY)
And the extra parens you added are unnecessary.

2024-11-05 12:49 UTC, NathanQingyangXu commented
> > > I think we should simply remove that log message. It's not useful, IMO.
> > 
> > 
> > If so, we could end up with lots of simplification to the ANTLR grammer, code or even perf.
> 
> WDYM?

nvm. I misunderstood. I'd thought we could move the keyword list to lexer file then I found it doesn't work.

2024-11-05 12:50 UTC, gavinking approved these changes
@NathanQingyangXu Please squash the commits and then we are good to go. Thanks!

2024-11-05 13:25 UTC, merged